BLOCK_SITE: []
DATABASE: sqlite
DEPLOY_TYPE: github
GITEE_FRIENDS_LINKS:
  enable: false
  owner: ccknbc
  repo: blogroll
  state: open
  type: normal
GITHUB_FRIENDS_LINKS:
  enable: false
  label: active
  owner: ccknbc
  repo: ccknbc-actions
  state: open
  type: normal
HTTP_PROXY: false
LINK:
- link: https://blog.bywind.xyz/link/
  theme: butterfly
- link: https://blog.bywind.xyz/link/
  theme: common1
- link: https://blog.bywind.xyz/link/
  theme: volantis
MAX_POSTS_NUM: 5
OUTDATE_CLEAN: 60
SETTINGS_FRIENDS_LINKS:
  enable: true
  json_api: ''
  list:
  - - "\u968F\u98CE\u8D77"
    - https://blog.bywind.xyz/
    - https://cloud-image-host.oss-cn-beijing.aliyuncs.com/wo.jpg
  - - "\u5F20\u6D2AHeo"
    - https://blog.zhheo.com/
    - https://img.zhheo.com/i/2022/08/19/62ff32fa28da1.png
  - - Jayhrn
    - https://blog.jayhrn.com
    - https://unpkg.com/jayblog-source@1.0.1/img/normal/avatar.webp
    - ''
  - - "\u5B89\u77E5\u9C7C`Blog"
    - https://anzhiy.cn/
    - https://image.anzhiy.cn/adminuploads/1/2022/09/15/63232b7d91d22.jpg
